[build-system]
requires = ["scikit-build", "cmake", "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aligncount_demo"
version = "0.1.0"
description = "Aligncount wrapper"

[project.scripts]
aligncount = "cli.entrypoint:main"