[build-system]
requires = [
    "setuptools>=42",
    "scikit-build>=0.13",
    "cmake>=3.18"
]
build-backend = "setuptools.build_meta"

[project]
name = "aligncount_demo"
version = "0.2.0"
description = "Aligncount wrapper"

[project.scripts]
aligncount = "cli.entrypoint:main"