{% set REPO_NAME   = environ.get('REPO_NAME',  'cpp-python-tool-template') %}
{% set VERSION     = environ.get('VERSION',    '0.2.37') %}
{% set TAR_URL     = environ.get('TAR_URL',    'https://github.com/vr1087/cpp-python-tool-template/archive/refs/tags/v0.2.37.tar.gz') %}
{% set SHA256      = environ.get('SHA256',     'c8bffc3e02bc465d0852fd124c354147a449b09e9847ff0ecaa747d083626f2a') %}
{% set REPO_HOME   = environ.get('REPO_HOME',  'https://github.com/vr1087/cpp-python-tool-template') %}

package:
  name: {{ REPO_NAME }}
  version: {{ VERSION }}

source:
  url:   {{ TAR_URL }}
  sha256: {{ SHA256 }}

build:
  skip: true  # [win]
  detect_python: False
  script: |
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
    cmake --build . --parallel ${CPU_COUNT:-1}
    cmake --install . --prefix $PREFIX
    cd ..
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - python
    - pip
    - setuptools
    - scikit-build
  host:
    - python
    - scikit-build
  run:
    - python

about:
  home: {{ REPO_HOME }}
  license: MIT
  summary: "C++ linecount + Python wrapper"
