{% set name = "aligncount-demo" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: <PLACEHOLDER>
  sha256: <PLACEHOLDER>

build:
  skip: true  # [not win]
  script: |
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
    cmake --build . --parallel ${CPU_COUNT:-1}
    cmake --install . --prefix $PREFIX
    cd ..
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - python >=3.10
    - pip
    - setuptools
    - scikit-build
  host:
    - python >=3.10
  run:
    - python >=3.10

about:
  home: <PLACEHOLDER>
  license: MIT
  summary: "C++ linecount + Python wrapper"
