{% set REPO_NAME   = environ.get('REPO_NAME',  'cpp-python-tool-template') %}
{% set VERSION     = environ.get('VERSION',    '0.0.1') %}
{% set TAR_URL     = environ.get('TAR_URL',    '') %}
{% set SHA256      = environ.get('SHA256',     '') %}
{% set REPO_HOME   = environ.get('REPO_HOME',  '') %}

package:
  name: {{ REPO_NAME }}
  version: {{ VERSION }}

source:
  url:   {{ TAR_URL }}
  sha256: {{ SHA256 }}

build:
  skip: true  # [win]
  script: |
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
    cmake --build . --parallel ${CPU_COUNT:-1}
    cmake --install . --prefix $PREFIX
    cd ..
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - python >=3.9,<=3.13
    - pip
    - setuptools
    - scikit-build
  host:
    - python >=3.9,<=3.13
    - scikit-build
  run:
    - python >=3.9,<=3.13

about:
  home: {{ REPO_HOME }}
  license: MIT
  summary: "C++ linecount + Python wrapper"
