{% set name = "aligncount-demo" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: <PLACEHOLDER>
  sha256: <PLACEHOLDER>

build:
  number: 0
  requirements:
    build:
      - {{ compiler("cxx") }}
      - cmake
      - python3
      - pip3
      - setuptools
      - scikit-build
    host:
      - python3
      - pip3
      - setuptools
      - scikit-build
    run:
      - python

  script: |
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
    cmake --build . --parallel ${CPU_COUNT:-1}
    cmake --install . --prefix $PREFIX
    cd ..
    pip3 install . --no-deps --ignore-installed -vv

about:
  home: <PLACEHOLDER>
  license: MIT
  summary: "C++ linecount + Python wrapper"
