name: CI Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # ---------------------------
      # Part 1: C++ Build & CTest
      # ---------------------------

      - name: Install C++ build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake git python3-dev python3-pip

      - name: Configure and build C++ code
        run: |
          cd cpp
          cmake -S standalone -B build/standalone -DCMAKE_BUILD_TYPE=Release
          cmake --build build/standalone

      - name: Run C++ unit tests with CTest
        run: |
          cmake -S test -B build/test
          cmake --build build/test
          CTEST_OUTPUT_ON_FAILURE=1 cmake --build build/test --target test

      # -----------------------------
      # Part 2: Python install & tests
      # -----------------------------

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create & activate virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools scikit-build pytest

      - name: Install package (C++ + Python wrapper) via pip
        run: |
          source venv/bin/activate
          pip install .

      - name: Run Python unit tests
        run: |
          source venv/bin/activate
          pytest -q
